#!/bin/bash
pushd /home/lichao/scratch/pami
rm -r motor_res motor_face motor_car motor_airplane
mkdir motor_res motor_face motor_car motor_airplane
popd

ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/car_test/ /home/lichao/scratch/pami/motor_car/ /home/lichao/scratch/pami/quad_train_car_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_airplane_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_airplane_net2_el_64.txt /home/lichao/scratch/pami/quad_train_airplane_global_summary_64.txt /home/lichao/scratch/pami/quad_train_airplane_voro_centers_64.txt|tee multi_airplane_car_64.txt
ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/airplane_test/ /home/lichao/scratch/pami/motor_airplane/ /home/lichao/scratch/pami/quad_train_airplane_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_airplane_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_airplane_net2_el_64.txt /home/lichao/scratch/pami/quad_train_airplane_global_summary_64.txt /home/lichao/scratch/pami/quad_train_airplane_voro_centers_64.txt|tee multi_airplane_airplane_64.txt
ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/face_test/ /home/lichao/scratch/pami/motor_face/ /home/lichao/scratch/pami/quad_train_face_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_airplane_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_airplane_net2_el_64.txt /home/lichao/scratch/pami/quad_train_airplane_global_summary_64.txt /home/lichao/scratch/pami/quad_train_airplane_voro_centers_64.txt|tee multi_airplane_face_64.txt
ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/motorbike_test/ /home/lichao/scratch/pami/motor_res/ /home/lichao/scratch/pami/quad_test_res_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_airplane_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_airplane_net2_el_64.txt /home/lichao/scratch/pami/quad_train_airplane_global_summary_64.txt /home/lichao/scratch/pami/quad_train_airplane_voro_centers_64.txt|tee multi_airplane_motorbike_64.txt

#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/car_test/ /home/lichao/scratch/pami/motor_car/ /home/lichao/scratch/pami/quad_train_car_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_car_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_car_net2_el_64.txt /home/lichao/scratch/pami/quad_train_car_global_summary_64.txt /home/lichao/scratch/pami/quad_train_car_voro_centers_64.txt|tee multi_car_car_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/airplane_test/ /home/lichao/scratch/pami/motor_airplane/ /home/lichao/scratch/pami/quad_train_airplane_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_car_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_car_net2_el_64.txt /home/lichao/scratch/pami/quad_train_car_global_summary_64.txt /home/lichao/scratch/pami/quad_train_car_voro_centers_64.txt|tee multi_car_airplane_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/face_test/ /home/lichao/scratch/pami/motor_face/ /home/lichao/scratch/pami/quad_train_face_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_car_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_car_net2_el_64.txt /home/lichao/scratch/pami/quad_train_car_global_summary_64.txt /home/lichao/scratch/pami/quad_train_car_voro_centers_64.txt|tee multi_car_face_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/motorbike_test/ /home/lichao/scratch/pami/motor_res/ /home/lichao/scratch/pami/quad_test_res_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_car_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_car_net2_el_64.txt /home/lichao/scratch/pami/quad_train_car_global_summary_64.txt /home/lichao/scratch/pami/quad_train_car_voro_centers_64.txt|tee multi_car_motorbike_64.txt
#
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/car_test/ /home/lichao/scratch/pami/motor_car/ /home/lichao/scratch/pami/quad_train_car_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_face_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_face_net2_el_64.txt /home/lichao/scratch/pami/quad_train_face_global_summary_64.txt /home/lichao/scratch/pami/quad_train_face_voro_centers_64.txt|tee multi_face_car_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/airplane_test/ /home/lichao/scratch/pami/motor_airplane/ /home/lichao/scratch/pami/quad_train_airplane_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_face_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_face_net2_el_64.txt /home/lichao/scratch/pami/quad_train_face_global_summary_64.txt /home/lichao/scratch/pami/quad_train_face_voro_centers_64.txt|tee multi_face_airplane_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/face_test/ /home/lichao/scratch/pami/motor_face/ /home/lichao/scratch/pami/quad_train_face_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_face_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_face_net2_el_64.txt /home/lichao/scratch/pami/quad_train_face_global_summary_64.txt /home/lichao/scratch/pami/quad_train_face_voro_centers_64.txt|tee multi_face_face_64.txt
#ruby process_rect.rb if draw_group_quality /home/lichao/scratch/pami/data/motorbike_test/ /home/lichao/scratch/pami/motor_res/ /home/lichao/scratch/pami/quad_test_res_64.txt /home/lichao/scratch/pami/quad_kmeans_800_64.txt nil /home/lichao/scratch/pami/quad_train_face_net2_raw_64.txt /home/lichao/scratch/pami/quad_train_face_net2_el_64.txt /home/lichao/scratch/pami/quad_train_face_global_summary_64.txt /home/lichao/scratch/pami/quad_train_face_voro_centers_64.txt|tee multi_face_motorbike_64.txt
#
